-- ──────────────────────────────────────────────────────────────────────────────
-- KyaPehnu – PostgreSQL Table Schema
-- Run this file once against your Neon project to provision the schema.
--
-- Anti-Gravity Rules enforced here:
--
--  1. RIGID ENUM GATES — `item_type_enum`, `season_enum`, and `category_enum`
--     are native PostgreSQL ENUM types. Any INSERT or UPDATE that supplies a
--     value outside the declared set will be rejected by the database engine
--     before it ever touches the application layer.
--
--  2. NO BLOB FOOTPRINTS — The `image_url` column is TEXT (not BYTEA).
--     Raw binary image data is never stored in Postgres. Only clean asset
--     pointer strings (Cloudinary URLs, Unsplash URLs, etc.) are persisted.
--
--  3. UNIQUE INDEX ANTI-BLOAT — A partial unique index on (image_url) plus a
--     composite unique constraint on (name, item_type, image_url) prevent
--     duplicate item uploads at the database layer, before the application
--     indexing layer can be polluted.
-- ──────────────────────────────────────────────────────────────────────────────

-- ── 1. Enum type definitions ─────────────────────────────────────────────────

-- Hard gate for clothing classification (mirrors VisionResult.clothing_type)
DO $$ BEGIN
  CREATE TYPE item_type_enum AS ENUM ('top', 'bottom', 'footwear', 'accessory');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Season relevance tags
DO $$ BEGIN
  CREATE TYPE season_enum AS ENUM ('spring', 'summer', 'autumn', 'winter', 'all');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Broad wardrobe category (maps to AddItemRequest.category)
DO $$ BEGIN
  CREATE TYPE category_enum AS ENUM ('top', 'bottom', 'footwear', 'accessory');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Occasion gate (mirrors OutfitSuggestion.occasion)
DO $$ BEGIN
  CREATE TYPE occasion_enum AS ENUM ('casual', 'formal', 'party', 'sport');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ── 2. wardrobe_items table ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS wardrobe_items (
  -- Primary key — UUID generated by the database for collision-free distributed writes
  id            UUID          PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Human-readable label (e.g. "White Oxford Shirt")
  name          TEXT          NOT NULL CHECK (char_length(name) BETWEEN 1 AND 120),

  -- Rigid classification — rejects anything outside the declared ENUM set
  item_type     item_type_enum NOT NULL,
  category      category_enum  NOT NULL,
  season        season_enum    NOT NULL DEFAULT 'all',

  -- Fine-grained sub-type resolved by the Two-Tier label engine.
  -- Stored as nullable TEXT — NOT an ENUM (per Anti-Gravity "No In-Database Type
  -- Hardcoding" rule). The full vocabulary lives in the Python resolver.
  -- Examples: 'cargo', 'jeans', 'polo-shirt', 'sneakers', 'hoodie'
  sub_type      TEXT,

  -- Dominant colour returned by the vision API (e.g. "#3a2f1c")
  hex_color     CHAR(7)        NOT NULL CHECK (hex_color ~ '^#[0-9a-fA-F]{6}$'),

  -- Human-readable colour name (e.g. "navy", "off-white")
  color_label   TEXT,

  -- Optional brand label
  brand         TEXT          CHECK (char_length(brand) <= 80),

  -- Tags stored as a native Postgres text array (queryable with ANY / @> operators)
  tags          TEXT[]        NOT NULL DEFAULT '{}',

  -- ⚠ TEXT ONLY — no binary blobs.
  -- Stores a web-accessible asset URL (Cloudinary / Unsplash / S3 public URL).
  -- Maximum length generously covers longest CDN URLs with transform parameters.
  image_url     TEXT          CHECK (
                                image_url IS NULL
                                OR (
                                  char_length(image_url) <= 2048
                                  AND image_url ~ '^https?://'
                                )
                              ),

  -- SHA-256 hex digest of the image file (computed before upload to CDN).
  -- Used by the unique constraint below to detect byte-identical re-uploads.
  image_hash    CHAR(64),

  is_favourite  BOOLEAN       NOT NULL DEFAULT FALSE,

  created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- ── 2a. Migration: add sub_type to existing wardrobe_items instances ─────────────
-- Safe to run multiple times on an already-provisioned Neon project.
-- ADD COLUMN IF NOT EXISTS is a Postgres 9.6+ no-op when the column exists.
DO $$ BEGIN
  ALTER TABLE wardrobe_items
    ADD COLUMN IF NOT EXISTS sub_type TEXT;
EXCEPTION WHEN others THEN NULL;
END $$;

-- ── 3. Indexes ───────────────────────────────────────────────────────────────

-- Fast lookups by item type (most common wardrobe filter)
CREATE INDEX IF NOT EXISTS idx_wardrobe_item_type
  ON wardrobe_items (item_type);

-- Fast lookups by season
CREATE INDEX IF NOT EXISTS idx_wardrobe_season
  ON wardrobe_items (season);

-- ── 4. Unique constraints — anti-duplicate layer ─────────────────────────────

-- Block identical image-hash re-uploads at the DB layer.
-- Partial index: only applies to rows where image_hash is not NULL.
CREATE UNIQUE INDEX IF NOT EXISTS uidx_wardrobe_image_hash
  ON wardrobe_items (image_hash)
  WHERE image_hash IS NOT NULL;

-- Composite guard: same name + same type + same image URL = duplicate record.
-- This prevents metadata bloat even when image_hash is absent (URL-sourced items).
CREATE UNIQUE INDEX IF NOT EXISTS uidx_wardrobe_name_type_image
  ON wardrobe_items (name, item_type, image_url)
  WHERE image_url IS NOT NULL;

-- ── 5. Auto-update trigger for updated_at ────────────────────────────────────

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_wardrobe_updated_at ON wardrobe_items;
CREATE TRIGGER trg_wardrobe_updated_at
  BEFORE UPDATE ON wardrobe_items
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ── 6. outfit_suggestions table (normalised) ─────────────────────────────────

CREATE TABLE IF NOT EXISTS outfit_suggestions (
  id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  occasion         occasion_enum NOT NULL,
  confidence_score NUMERIC(4,3)  NOT NULL CHECK (confidence_score BETWEEN 0 AND 1),
  style_note       TEXT          NOT NULL,
  created_at       TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- Junction table: one outfit ↔ many wardrobe items (many-to-many)
CREATE TABLE IF NOT EXISTS outfit_items (
  outfit_id UUID NOT NULL REFERENCES outfit_suggestions (id) ON DELETE CASCADE,
  item_id   UUID NOT NULL REFERENCES wardrobe_items    (id) ON DELETE CASCADE,
  PRIMARY KEY (outfit_id, item_id)
);
